### ISSUE TITLE
Custom page level metadata not being added

### ISSUE THREAD

**Issue by francodacosta** [matt-j-m/grav-plugin-aura#2] opened 2019-10-17 07:33 UTC
Custom metadata added via the page options tabs is not part of the html when Aura plugin is enabled

**Comment by matt-j-m** [comment] 2020-02-09 05:28
Hi @francodacosta thank you for noting this. The issue is now resolved in latest release v1.0.2.

**Closed as completed by matt-j-m** 2020-02-09 05:28 UTC
Labels: bug
